default: &default
  username: dev
  password: el0pm3nt
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pasapp_development

test:
  <<: *default
  database: pasapp_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
